services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: wifi_access_points
        MYSQL_USER: admin
        MYSQL_PASSWORD: P4ssw0rd@
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        interval: 10s
        timeout: 5s
        retries: 5

  app:
    build: .
    container_name: graph_ql_api
    restart: always
    depends_on:
          mysql:
            condition: service_healthy
    environment:
          SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/wifi_access_points?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
          SPRING_DATASOURCE_USERNAME: admin
          SPRING_DATASOURCE_PASSWORD: P4ssw0rd@
    ports:
        - "8080:8080"
    networks:
        - app_network
volumes:
  mysql_data:

networks:
    app_network:
