spring:
  datasource:
    url: jdbc:mysql://localhost:3307/wifi_access_points?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: P4ssw0rd@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
       format_sql: true
       use_sql_comments: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect
  graphql:
    path: /graphql
    graphiql:
     enabled: true
  sql:
    init:
      mode: always
server:
  port: 8080
app:
 files:
  csv-path: classpath:data/puntos_de_acceso_wifi.csv
  graphql-path: classpath:graphql/query.graphqls
  sqlfile-path: 2024-06-30-puntos_de_acceso_wifi.sql

pagination:
  default-page: 0
  default-size: 10

logging:
  level:
    '[com.develop]': DEBUG
    '[org.springframework.jdbc]': DEBUG
    #'[graphql.execution]': DEBUG
    #'[org.hibernate.SQL]': DEBUG